modLoader="javafml"
loaderVersion="[${forgeMinVersion},)"
license="${modLicense}"
issueTrackerURL="https://github.com/${modGitHub}/issues"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
logoFile="assets/rethink_config_ui_lib/icon.png"
authors="${modAuthor}"
description='''${modDescription}'''
displayURL="https://github.com/${modGitHub}"

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="[${forgeMinVersion},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRangeForge}"
ordering="NONE"
side="CLIENT"
