enable_platforms=fabric,forge,neoforge
minecraft_version=26.1.2
resource_pack_format=84
publish_version=26.1,26.1.1,26.1.2
minecraft_version_range_fabric=>=26.1 <26.2
minecraft_version_range_forge=[26.1,26.2)
minecraft_version_range_neoforge=[26.1,26.2)
deps.parchment=
deps.fabric-loader=0.19.2
deps.fabric-loader-min=0.11.0
deps.fabric-api=0.145.1+26.1
deps.modmenu=18.0.0
deps.forge=64.1.2
deps.forge-min=64
deps.neoforge=26.1.2.97
deps.neoforge-min=26.1
