enable_platforms=fabric,forge
minecraft_version=1.14.4
publish_version=1.14.4
minecraft_version_range_fabric=1.14.4
minecraft_version_range_forge=[1.14.4]
deps.parchment=
deps.fabric-loader=0.16.10
deps.fabric-loader-min=0.14.0
deps.fabric-api=0.28.5+1.14
deps.modmenu=1.14.14
deps.forge=28.2.30
deps.forge-min=28
