enable_platforms=fabric,forge,neoforge
minecraft_version=26.2
publish_version=26.2
minecraft_version_range_fabric=>=26.2
minecraft_version_range_forge=[26.2,26.3)
minecraft_version_range_neoforge=[26.2,26.3)
deps.parchment=
deps.fabric-loader=0.19.3
deps.fabric-loader-min=0.11.0
deps.fabric-api=0.158.0+26.2
deps.modmenu=20.0.1
deps.forge=65.1.2
deps.forge-min=65
deps.neoforge=26.2.0.63
deps.neoforge-min=26.2
