enable_platforms=fabric,forge
minecraft_version=1.15.2
publish_version=1.15.2
minecraft_version_range_fabric=1.15.2
minecraft_version_range_forge=[1.15.2]
deps.parchment=
deps.fabric-loader=0.16.10
deps.fabric-loader-min=0.14.0
deps.fabric-api=0.28.5+1.15
deps.modmenu=1.10.6
deps.forge=31.2.62
deps.forge-min=31
