enable_platforms=fabric,neoforge
minecraft_version=26.3
resource_pack_format=97
resource_pack_format_minor=1
publish_version=26.3
minecraft_version_range_fabric=>=26.3 <26.4
minecraft_version_range_forge=[26.3,26.4)
minecraft_version_range_neoforge=[26.3,26.4)
deps.parchment=
deps.fabric-loader=0.19.5
deps.fabric-loader-min=0.14.0
deps.fabric-api=0.160.5+26.3
deps.modmenu=21.0.0-beta.1
deps.forge=
deps.forge-min=
deps.neoforge=26.3.0.1-beta
deps.neoforge-min=26.3
